### PR TITLE
Update tokens.json

### PR DESCRIPTION
**Pull request by sumandobanzar**

### CODE REVIEW

**Review by Cordtus — CHANGES_REQUESTED** [review]
Please add a logo also for the token here --
https://github.com/cac-group/front-end-utils/tree/main/logos

**Comment by sumandobanzar** [comment]
DONE 

sorry, i'm newbie but i try

**Comment by Cordtus** [comment]
Thanks looks good app should update shortly

**Review by Cordtus — COMMENTED** [review]
Wonder how the square image will turn out. I think the rest are circular.

**Review by sumandobanzar — COMMENTED** [review]
kleo

**Comment by sumandobanzar** [comment]
> Wonder how the square image will turn out. I think the rest are circular.

kleo

**Pull request merged**
